blank issues enabled: false
contact links:
	name: GitHub Community Forum
	url: https: //github.community/
	about: Please ask and answer questions here.
	name: GitHub Security Bug Bounty
	ur: https://bounty.github.com/
	about: Please report security vulnerabllaties here
	name: GitHub Security Bug Bounty
	ur: https://bounty.github.com/
	about: Please report security vulnerabllaties here
