name: "Feature Request"
description: "A new feature"
labels: ["Feature"]
body:
- type: markdown
  attributes:
    value: "# Features\n"
- type: checkboxes
  id: cat-preferences
  attributes:
    label: What kinds of cats do you like?
    description: You may select more than one.
    options:
      - label: Orange cat (required. Everyone likes orange cats.)
        required: true
      - label: Black cat
- type: "textarea"
  id: Features
  attributes:
    label: What happened?
    description: Also tell us, what did you expect to happen?
    placeholder: Tell us what you see!
    value: "A bug happened!"
  validations:
    required: true
