name: "Feature Request"
description: "A new feature"
labels: ["Feature"]
body:
- type: "textarea"
  id: Features
  attributes:
    label: What happened?
    description: Also tell us, what did you expect to happen?
    placeholder: Tell us what you see!
    value: "A bug happened!"
  validations:
    required: true
- type: checkboxes
  id: browsers
  attributes:
    label: Browsers & Devices
    description: Check all browsers & devices been tested on
    options:
      - label: Chrome (Desktop)
        required: true
      - label: Safari (Desktop)
        required: true
      - label: Edge (Desktop)
        required: true
      - label: Firefox (Desktop)
        required: true
      - label: Chrome (Mobile)
        required: true
      - label: Safari (Mobile)
        required: true
      - label: Min Screen Width (320px min)
        required: true
      - label: Max Screen Width (1920px min)
        required: true

